---

- name: config | Configure monitoring "{{ item.name }}"
  template:
    src: etc/monit/conf-available/conf.j2
    dest: "/etc/monit/conf-available/{{ item.name }}"
  notify:
    - Reload Monit
  tags:
    - monit
    - configs

- name: config | Enable monitoring "{{ item.name }}"
  file:
    src: "/etc/monit/conf-available/{{ item.name }}"
    dest: "/etc/monit/conf-enabled/{{ item.name }}"
    state: link
  notify:
    - Reload Monit
  tags:
    - monit
    - configs
