---

- include: install.yml
- include: mail.yml
- include: configs.yml
  with_items:
    - "{{ monit_default_configs }}"

- include: configs.yml
  with_items:
    - "{{ monit_configs }}"

- include: webserver.yml
  when: monit_enble_webserver
