---

- name: webserver | Configure Monit webservice
  template:
    src: etc/monit/conf.d/webserver.j2
    dest: /etc/monit/conf.d/webserver.conf
  notify:
    - Reload Monit
  tags:
    - monit
    - webserver
